project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Alyssa Han"
  site-url: https://alyssahsy.github.io
  repo-url: https://github.com/alyssahsy/alyssahsy.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2026, Alyssa Han"
    right: 
      - icon: github
        href: https://github.com/alyssahsy/alyssahsy.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      
      - text: "Blog"
        href: blog/blog.qmd
        
      - text: "Recreation"
        href: recreation/recreation.qmd

      - text: "Resources"
        href: resources/resources.qmd

      # - text: "About me"
      #   href: about_me.qmd
        


format:
  html:
    theme: styles.scss


